"""add_length_constraint_to_recipe_notes_field

Revision ID: 2e3ac317ae24
Revises: 8a81d70e1bd9
Create Date: 2026-03-20 21:21:22.602612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3ac317ae24'
down_revision: Union[str, None] = '8a81d70e1bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10000),
               existing_nullable=True)

    with op.batch_alter_table('user_recipe_ratings', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_user_recipe_rating', ['user_id', 'recipe_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipe_ratings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_recipe_rating', type_='unique')
        batch_op.alter_column('notes',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.String(length=10000),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('auth_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
