"""add auth audit log table

Revision ID: 425f03cb4131
Revises: 54b1aec40fe3
Create Date: 2026-03-17 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425f03cb4131'
down_revision: Union[str, None] = 'c311fe2f102d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_audit_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_audit_logs_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_audit_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_audit_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_audit_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_auth_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_auth_audit_logs_email'))
        batch_op.drop_index(batch_op.f('ix_auth_audit_logs_created_at'))

    op.drop_table('auth_audit_logs')
    # ### end Alembic commands ###
