"""add index to substitution_preferences user_id

Revision ID: 6d1e7e4f7827
Revises: 1bf9b813a278
Create Date: 2026-03-18 17:00:53.734930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1e7e4f7827'
down_revision: Union[str, None] = '1bf9b813a278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitution_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substitution_preferences_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitution_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_substitution_preferences_user_id'))

    # ### end Alembic commands ###
