"""add account lockout fields

Revision ID: c311fe2f102d
Revises: 54b1aec40fe3
Create Date: 2026-03-17 20:44:39.541918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c311fe2f102d'
down_revision: Union[str, None] = '54b1aec40fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add failed_login_attempts with server default for existing users
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lockout_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
