"""add lockout_count field

Revision ID: d4a8c9e2b5f1
Revises: 6d1e7e4f7827
Create Date: 2026-03-18 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a8c9e2b5f1'
down_revision: Union[str, None] = '6d1e7e4f7827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add lockout_count to track number of lockout events for progressive duration
        batch_op.add_column(sa.Column('lockout_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lockout_count')

    # ### end Alembic commands ###
