"""initial schema

Revision ID: eb9402f07ab3
Revises: 
Create Date: 2026-03-15 14:22:01.400878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9402f07ab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_patterns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('purchase_dates', sa.JSON(), nullable=False),
    sa.Column('depletion_dates', sa.JSON(), nullable=False),
    sa.Column('avg_interval_days', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('notification_threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('has_digital_receipts', sa.Boolean(), nullable=False),
    sa.Column('parsing_profile', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('dietary_profile', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('disliked_ingredients', sa.JSON(), nullable=False),
    sa.Column('favorite_ingredients', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vegan_friendly', sa.Boolean(), nullable=False),
    sa.Column('storage_location', sa.String(length=50), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('frozen_date', sa.DateTime(), nullable=True),
    sa.Column('is_staple', sa.Boolean(), nullable=False),
    sa.Column('minimum_threshold', sa.Float(), nullable=True),
    sa.Column('shareability', sa.String(length=50), nullable=False),
    sa.Column('reserved_for', sa.Uuid(), nullable=True),
    sa.Column('reserved_note', sa.String(length=500), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('preferred_store', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preferred_store'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_image', sa.String(length=2048), nullable=True),
    sa.Column('variation_groups', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('base_servings', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('nutritional_info', sa.JSON(), nullable=True),
    sa.Column('times_cooked', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substitution_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_ingredient', sa.String(length=255), nullable=False),
    sa.Column('replacements', sa.JSON(), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_meal_plan_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('candidate_recipes', sa.JSON(), nullable=False),
    sa.Column('user_rankings', sa.JSON(), nullable=False),
    sa.Column('draft_plan', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_store_association',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('inventory_item_id', 'store_id')
    )
    op.create_table('prepared_foods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_recipe', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('servings_remaining', sa.Float(), nullable=False),
    sa.Column('storage_location', sa.String(length=50), nullable=False),
    sa.Column('date_prepared', sa.DateTime(), nullable=False),
    sa.Column('estimated_expiration', sa.DateTime(), nullable=True),
    sa.Column('shareability', sa.String(length=50), nullable=False),
    sa.Column('prepared_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_recipe'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('variation_group', sa.String(length=100), nullable=True),
    sa.Column('variation_diet', sa.String(length=50), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_recipe_ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('prepared_food_id', sa.Uuid(), nullable=True),
    sa.Column('planned_servings', sa.Integer(), nullable=False),
    sa.Column('make_extra', sa.Boolean(), nullable=False),
    sa.Column('extra_servings_purpose', sa.String(length=500), nullable=True),
    sa.Column('user_variations', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('leftovers_generated', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['leftovers_generated'], ['prepared_foods.id'], ),
    sa.ForeignKeyConstraint(['prepared_food_id'], ['prepared_foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grocery_list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('linked_recipe', sa.Uuid(), nullable=True),
    sa.Column('linked_meal_plan_entry', sa.Uuid(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('target_store', sa.Uuid(), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('purchased_by', sa.Uuid(), nullable=True),
    sa.Column('purchased_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_meal_plan_entry'], ['meal_plan_entries.id'], ),
    sa.ForeignKeyConstraint(['linked_recipe'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['purchased_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_store'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_user_association',
    sa.Column('meal_plan_entry_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_entry_id'], ['meal_plan_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('meal_plan_entry_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan_user_association')
    op.drop_table('grocery_list_items')
    op.drop_table('meal_plan_entries')
    op.drop_table('user_recipe_ratings')
    op.drop_table('recipe_ingredients')
    op.drop_table('prepared_foods')
    op.drop_table('inventory_store_association')
    op.drop_table('weekly_meal_plan_votes')
    op.drop_table('substitution_preferences')
    op.drop_table('recipes')
    op.drop_table('inventory_items')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('consumption_patterns')
    # ### end Alembic commands ###
